### ISSUE TITLE
Usage in Colab

### ISSUE THREAD

**Issue by AkiMosi** [jsexauer/networkx_viewer#18]
Hello, found this module to be so helpful. I tried to use it in Google Colab but got some errors. Can it be used in Colab ?

**Comment by jsexauer** [comment]
Sorry, I have never tried it.  Can you run apps written with tkinter in Colab?

**Comment by AkiMosi** [comment]
> Sorry, I have never tried it. Can you run apps written with tkinter in Colab?

I think we can't. Yet your work is so good.
