### ISSUE TITLE
New Version for networkx v2

### ISSUE THREAD

**Issue by afeser** [jsexauer/networkx_viewer#19]
Hi, firstly I thank to maintainers to provide such a useful library.

I want to contribute to make it to compatible with networkx version 2. Unfortunately, adding `if nx.__version__ == '1.11'` tags made the code very unreadable. Therefore, I thought it is best to release a new version if it is ok.

I do not have any prior knowledge in version hierarchy, should I simply write the code and open a pull request or anything else is required?

Currently, I created a new branch that works fine with networkx_v2 with python3 on Fedora 31 Workstation. I think there is another option to maintain this version as a separate branch.

Regards,

**Comment by jsexauer** [comment]
thank you very much for the PR.  I will review it in a few days.

**Comment by jsexauer** [comment]
thank you again so much for writing most of the code to get this working with network viewer 2.  I made a few additional changes to get the units tests to work and a few of the UI features you missed.  I've released a new version 0.3.0
